---
- name: Exercise 3b
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Gather show version output
      nxos_command:
        commands: 
          - show version
          - show lldp neighbors
      register: show_output

    - debug:
        var: show_output     
