---
- name: Exercise 5b
  hosts: juniper
  gather_facts: False
  tasks:
    - junos_command:
        commands: show interfaces terse
      register: interfaces

    - debug:
        msg: "Primary IP: {{ interfaces['stdout_lines'][0][-1] }}"
